[package]
name = "circle-plonk-dsl-constraint-system"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
stwo.workspace = true
stwo-examples.workspace = true
num-traits.workspace = true